site_name: d-sys.wiki
site_url: https://d-sys.wiki
copyright: "github/x: @captradeoff"
site_author: captradeoff
repo_url: https://github.com/captradeoff/d-sys-wiki
edit_uri: edit/master/docs/
docs_dir: wiki

nav:
  - home: "index.md"
  - fundamentals:
      - Index: "fundamentals/index.md"
  - llms: "llms.txt"
  - rss: "feed_rss_updated.xml"
  
plugins:
  - rss
  - llmstxt:
      files:
        - output: llms.txt
          inputs:
            - '**.md'
  - search
  - git-revision-date
  - spellcheck:

theme:
  name: terminal
  custom_dir: theme
  palette: gruvbox_dark
  features:
    - footer.prev_next
    - navigation.side.indexes
    - navigation.top.cursor_animation.hide
    - revision.date
    - revision.history

markdown_extensions:
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
