site_name: d-sys.wiki
site_url: https://d-sys.wiki
copyright: 'github/x: @captradeoff'
site_author: captradeoff
repo_url: https://github.com/captradeoff/d-sys-wiki  
edit_uri: edit/master/docs/
docs_dir: wiki

nav:
    - home: 'index.md'
    - fundamentals:
       - 'what are distributed systems?': 'fundamentals/distributed-systems.md'
plugins:
  - search
  - git-revision-date
  - spellcheck:

theme:
  name: terminal
  palette: gruvbox_dark
  features:
    - footer.prev_next
    - navigation.side.indexes
    - navigation.top.cursor_animation.hide
    - revision.date
    - revision.history
