site_name: d-sys.wiki
site_url: https://d-sys.wiki
copyright: "this work is dedicated to the public domain under CC0 1.0."
site_author: captradeoff
repo_url: https://github.com/captradeoff/d-sys-wiki
edit_uri: edit/master/docs/
docs_dir: wiki

nav:
  - home: "index.md"
  - fundamentals:
      - Index: "fundamentals/index.md"
  - llms: "llms.txt"
  - rss: "feed_rss_updated.xml"

plugins:
  - ultralytics:
      verbose: True
      enabled: True
      default_image: "https://d-sys.wiki/img/captradeoff.jpg"
      default_author: "@captradeoff"
      add_desc: True
      add_image: True
      add_keywords: True
      add_share_buttons: False
      add_json_ld: True
  - rss
  - llmstxt:
      files:
        - output: llms.txt
          inputs:
            - "**.md"
  - search
  - git-revision-date
  - spellcheck:

theme:
  name: terminal
  custom_dir: theme
  palette: gruvbox_dark
  features:
    - footer.prev_next
    - navigation.side.indexes
    - navigation.top.cursor_animation.hide
    - revision.date
    - revision.history

markdown_extensions:
  - md_in_html
  - toc:
      permalink: "⁂"
      permalink_title: Anchor link to this section for reference

extra_css:
  - style.css

extra:
  social:
    image: wiki/img/captradeoff.png
    description: "public domain distributed systems wiki with notes, research, and code"
    title: "d-sys.wiki – all things distributed systems"
