name: x

on:
  push:
    branches:
      - master

jobs:
  post-diff-summary-to-x-community:
    runs-on: ubuntu-latest
    name: post-diff
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get diff
        id: get-diff
        run: |
          # Get the diff between the current commit and its parent, only for wiki/ directory
          DIFF=$(git diff HEAD^ HEAD -- wiki/)
          # Check if diff is empty
          if [ -z "$DIFF" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in wiki directory. Skipping post to X."
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            # Trim the diff to a reasonable size (first 10000 characters)
            TRIMMED_DIFF="${DIFF:0:10000}"
            # Set the diff as an output
            echo "diff<<EOF" >> $GITHUB_OUTPUT
            echo "$TRIMMED_DIFF" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Explain Diff
        id: explain
        if: steps.get-diff.outputs.has_changes == 'true'
        uses: captradeoff/openai-summarize-diff-action@v0.7
        with:
          diff: ${{ steps.get-diff.outputs.diff }}
          apikey: ${{ secrets.OPENAI_APIKEY }}
          maxTokens: 50
          maxCharacters: 140
          examplePostSummary: |-
            wiki content updated:
              - cap theorem: what it means, how to apply it
              - use cases for a distributed database
              - code sample of a load balancer

      - name: x post step
        id: x
        if: steps.get-diff.outputs.has_changes == 'true'
        uses: captradeoff/x-post-action@v0.7
        with:
          appKey: ${{ secrets.X_APP_KEY }}
          appSecret: ${{ secrets.X_APP_SECRET }}
          accessToken: ${{ secrets.X_ACCESS_TOKEN }}
          accessSecret: ${{ secrets.X_ACCESS_SECRET }}
          message: ${{ steps.explain.outputs.explanation }}
          community-id: "1903531139035476424"

      - name: Get the output post-id
        if: steps.get-diff.outputs.has_changes == 'true'
        run: echo "The post-id was ${{ steps.x.outputs.post-id }}"
