name: x
on:
  push:
    branches:
      - master 
jobs:
  x_post_action_job:
    runs-on: ubuntu-latest
    name: post
    steps:
      - name: x post step
        id: x
        uses: captradeoff/x-post-action@v0.2
        with:
          message: 'getting set up'
          community-id: 1903531139035476424
      - name: Get the output post-id
        run: echo "The post-id was ${{ steps.x.outputs.post-id }}"
