name: x

on:
  push:
    branches:
      - master

env:
  DIFF: ${{ compare(github.base_ref, github.head_ref) }}

jobs:
  x_post_action_job:
    runs-on: ubuntu-latest
    name: post
    steps:
      - name: Explain Diff
        id: explain
        uses: captradeoff/openai-summarize-diff-action@v0.1
        with:
          diff: ${{ env.DIFF }}
          apikey: ${{ secrets.OPENAI_APIKEY }}
      - name: x post step
        id: x
        uses: captradeoff/x-post-action@v0.7
        with:
          appKey: ${{ secrets.X_APP_KEY }}
          appSecret: ${{ secrets.X_APP_SECRET }}
          accessToken: ${{ secrets.X_ACCESS_TOKEN }}
          accessSecret: ${{ secrets.X_ACCESS_SECRET }}
          message: steps.explain.outputs.explanation
          community-id: "1903531139035476424"
      - name: Get the output post-id
        run: echo "The post-id was ${{ steps.x.outputs.post-id }}"
